### ISSUE TITLE
Bad colorb_v data and absmag strangeness

### ISSUE THREAD

**Issue by f-koehler** [HacktheUniverse/star-api#41]
Before I start, I am not an astronomer so the faults may lay on my side.

I tried to create a Hertzsprung–Russell diagram from all the 100,000+ stars you provide. But the data for colorv_b seems to be very unprecise as I get vertical stripes in the plot. Looking into the raw JSON I see that this value only has two digits behind the comma. Is there any chance we get better data?

![hr](https://cloud.githubusercontent.com/assets/5512292/7447417/66ebacc8-f1fb-11e4-81a4-8c53dcbab762.png)

Second I found out that one particular star seems to have a wrong absmag or lum value (I would expect an exponential law, which would appear to be linear in a logarithmic plot). One point is quite some distance away from the line (absmag≈15.1 lum≈10^-2). Is this a mistake?

![absmag](https://cloud.githubusercontent.com/assets/5512292/7447422/ad805abc-f1fb-11e4-88ee-dcffeb5d41b0.png)

**Comment by surenm** [comment]
Hey @f-koehler, The actual data is available here - http://research.amnh.org/users/abbott/dudata/milkyway/specks/stars.speck

I don't think we are losing any precision when we serve this over the API. I roughly checked it for a few stars. Similarly for the possible mistake in the luminosity data, I don't think its on the API end. If you could find the exact star that seems anomalous, we could talk to Brian from AMNH and see what he thinks about that.

PS: Thanks for filing the bug and sorry for the delay. Would love the API to be working correct and in case the data source isn't correct, would like to connect you with people who can fix that.
