### ISSUE TITLE
Define Variables

### ISSUE THREAD

**Issue by isaachinman** [HacktheUniverse/star-api#43]
Hi there, I am currently building an app that uses this API, and would like some clarification on variables. Surprisingly I cannot find much in the documentation. As far as I can tell:

```
absmag: "4.85" -------------- ABSOLUTE MAGNITUDE
appmag: "-26.72" ------------ APPARENT MAGNITUDE
colorb_v: "0.65" ------------ COLOUR
created_at: "49:09.3" ------- CREATED AT
dcalc: "0"
distance_light_years: "0" --- DISTANCE
hipnum: "0" ----------------- HIPPARCOS NUMBER
id: "53794" ----------------- UNIQUE ID
label: "Sun" ---------------- NAME
luminosity: "0.8913" -------- LUMINOSITY
plx: "0" -------------------- PARALLAX
plxerr: "0" ----------------- PARALLAX MARGIN OF ERROR
speed: "0" ------------------ SPEED
texnum: "1"
updated_at: "49:09.3" ------- UPDATED AT
```

Is this the case? Can you explain the dcalc and texnum variables? Also, the example filter section seems to indicate that for colorb_v, 0 is blue, 1 is red, but in reality the stars in the database range from -.63 to 2.057. Is this meant to indicate light being emitted outside the visible spectrum?

Also, I noticed another issue on here had to do with colour in RGB values. I only just saw this, but have already put together a function that receives the star's colorb_v value and interpolates it across a spectrum of possible star colours. I can share that if you'd like. Cheers!

**Comment by surenm** [comment]
Hey @isaachinman, Happy that you are putting the API to good use :+1: 

We were only mere computer programmers ourselves, so we don't fully understand the significance of these fields. But that said, we got every thing we needed from the DU data set which you can download here - http://www.amnh.org/our-research/hayden-planetarium/digital-universe/download

Specifically https://github.com/HacktheUniverse/star-api/blob/master/docs/Digital%20Universe%20Guide.pdf page no 69 has references you might need. You may also be able to understand how colorb_v values are to be interpreted by going through the stars.speck file overview on that same PDF file.

Let me know if this helps!

**Comment by isaachinman** [comment]
@surenm Great, I'll take a look through the dataset and these docs. Cheers.

**Comment by isaachinman** [comment]
@surenm I'm having trouble understanding the luminosity variable. It is scaled, but it's unclear if the scale is linear or logarithmic. Moreover, neither Vega nor the Sun are defined as 1, so I'm not sure what the constant is. [The documentation](https://github.com/HacktheUniverse/star-api/blob/master/docs/Digital%20Universe%20Guide.pdf) seems to imply that a constant can be set:

"With a constant luminosity set, you may now toggle between them by typing lum const and lum lum."

Do you know what the lum const is set to in this instance?

**Comment by isaachinman** [comment]
@surenm Just wanted to readdress this - I got in touch with Brian Abbott at AMNH, and he told me that the museum was not aware the dataset was being used. I need a reference point for the luminosity value to be able to calculate star radii. I have no idea what the lum constant has been set to, and neither do the people over at AMNH. Any ideas?
